USE EmployeeTracker;

DROP TABLE IF EXISTS role;

CREATE TABLE role (
    id INTEGER AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
    title VARCHAR(64) NOT NULL,
    salary DECIMAL DEFAULT 0.00,
    department_id INTEGER
);
